<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9lelAqa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9lelAqa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9lelAqa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9lelAqa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9lelAqa\App_KernelDevDebugContainer([
    'container.build_hash' => '9lelAqa',
    'container.build_id' => '4a4e2471',
    'container.build_time' => 1585701293,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9lelAqa');
